"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager
from .._callback_context import context_value as _ctx
from .._utils import AttributeDict as _AD

@contextmanager
def ignore_register_page(): # -> Generator[None, Any, None]:
    ...

