"""
This type stub file was generated by pyright.
"""

from .managers.celery_manager import CeleryLongCallbackManager, CeleryManager
from .managers.diskcache_manager import DiskcacheLongCallbackManager, DiskcacheManager

