"""
This type stub file was generated by pyright.
"""

class ProxySetProps(dict):
    """
    Defer dictionary item setter to run a custom function on change.
    Used by background callback manager to save the `set_props` data.
    """
    def __init__(self, on_change) -> None:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    


