"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING

import ipywidgets as _ipywidgets
from packaging.version import Version as _Version

from . import bar as bar
from . import barpolar as barpolar
from . import box as box
from . import candlestick as candlestick
from . import carpet as carpet
from . import choropleth as choropleth
from . import choroplethmapbox as choroplethmapbox
from . import cone as cone
from . import contour as contour
from . import contourcarpet as contourcarpet
from . import densitymapbox as densitymapbox
from . import funnel as funnel
from . import funnelarea as funnelarea
from . import heatmap as heatmap
from . import heatmapgl as heatmapgl
from . import histogram as histogram
from . import histogram2d as histogram2d
from . import histogram2dcontour as histogram2dcontour
from . import icicle as icicle
from . import image as image
from . import indicator as indicator
from . import isosurface as isosurface
from . import layout as layout
from . import mesh3d as mesh3d
from . import ohlc as ohlc
from . import parcats as parcats
from . import parcoords as parcoords
from . import pie as pie
from . import pointcloud as pointcloud
from . import sankey as sankey
from . import scatter as scatter
from . import scatter3d as scatter3d
from . import scattercarpet as scattercarpet
from . import scattergeo as scattergeo
from . import scattergl as scattergl
from . import scattermapbox as scattermapbox
from . import scatterpolar as scatterpolar
from . import scatterpolargl as scatterpolargl
from . import scattersmith as scattersmith
from . import scatterternary as scatterternary
from . import splom as splom
from . import streamtube as streamtube
from . import sunburst as sunburst
from . import surface as surface
from . import table as table
from . import treemap as treemap
from . import violin as violin
from . import volume as volume
from . import waterfall as waterfall
from ._bar import Bar as Bar
from ._barpolar import Barpolar as Barpolar
from ._box import Box as Box
from ._candlestick import Candlestick as Candlestick
from ._carpet import Carpet as Carpet
from ._choropleth import Choropleth as Choropleth
from ._choroplethmapbox import Choroplethmapbox as Choroplethmapbox
from ._cone import Cone as Cone
from ._contour import Contour as Contour
from ._contourcarpet import Contourcarpet as Contourcarpet
from ._densitymapbox import Densitymapbox as Densitymapbox
from ._deprecations import (
    AngularAxis,
    Annotation,
    Annotations,
    ColorBar,
    Contours,
    Data,
    ErrorX,
    ErrorY,
    ErrorZ,
    Font,
    Frames,
    Histogram2dcontour,
    Legend,
    Line,
    Margin,
    Marker,
    RadialAxis,
    Scene,
    Stream,
    Trace,
    XAxis,
    XBins,
    YAxis,
    YBins,
)
from ._deprecations import ZAxis as ZAxis
from ._figure import Figure as Figure
from ._frame import Frame as Frame
from ._funnel import Funnel as Funnel
from ._funnelarea import Funnelarea as Funnelarea
from ._heatmap import Heatmap as Heatmap
from ._heatmapgl import Heatmapgl as Heatmapgl
from ._histogram import Histogram as Histogram
from ._histogram2d import Histogram2d as Histogram2d
from ._histogram2dcontour import Histogram2dContour as Histogram2dContour
from ._icicle import Icicle as Icicle
from ._image import Image as Image
from ._indicator import Indicator as Indicator
from ._isosurface import Isosurface as Isosurface
from ._layout import Layout as Layout
from ._mesh3d import Mesh3d as Mesh3d
from ._ohlc import Ohlc as Ohlc
from ._parcats import Parcats as Parcats
from ._parcoords import Parcoords as Parcoords
from ._pie import Pie as Pie
from ._pointcloud import Pointcloud as Pointcloud
from ._sankey import Sankey as Sankey
from ._scatter import Scatter as Scatter
from ._scatter3d import Scatter3d as Scatter3d
from ._scattercarpet import Scattercarpet as Scattercarpet
from ._scattergeo import Scattergeo as Scattergeo
from ._scattergl import Scattergl as Scattergl
from ._scattermapbox import Scattermapbox as Scattermapbox
from ._scatterpolar import Scatterpolar as Scatterpolar
from ._scatterpolargl import Scatterpolargl as Scatterpolargl
from ._scattersmith import Scattersmith as Scattersmith
from ._scatterternary import Scatterternary as Scatterternary
from ._splom import Splom as Splom
from ._streamtube import Streamtube as Streamtube
from ._sunburst import Sunburst as Sunburst
from ._surface import Surface as Surface
from ._table import Table as Table
from ._treemap import Treemap as Treemap
from ._violin import Violin as Violin
from ._volume import Volume as Volume
from ._waterfall import Waterfall as Waterfall

if sys.version_info < (3, 7) or TYPE_CHECKING: ...
else: ...
if sys.version_info < (3, 7) or TYPE_CHECKING: ...
else: ...
