"""
This type stub file was generated by pyright.
"""

from .messages import Message
from .midifiles import MetaMessage, UnknownMetaMessage

class Frozen:
    def __setattr__(self, *_):
        ...
    
    def __hash__(self) -> int:
        ...
    


class FrozenMessage(Frozen, Message):
    ...


class FrozenMetaMessage(Frozen, MetaMessage):
    ...


class FrozenUnknownMetaMessage(Frozen, UnknownMetaMessage):
    def __repr__(self): # -> str:
        ...
    


def is_frozen(msg): # -> bool:
    """Return True if message is frozen, otherwise False."""
    ...

def freeze_message(msg): # -> Frozen | FrozenMessage | FrozenUnknownMetaMessage | FrozenMetaMessage | None:
    """Freeze message.

    Returns a frozen version of the message. Frozen messages are
    immutable, hashable and can be used as dictionary keys.

    Will return None if called with None. This allows you to do things
    like::

        msg = freeze_message(port.poll())
    """
    ...

def thaw_message(msg): # -> Message | UnknownMetaMessage | MetaMessage | None:
    """Thaw message.

    Returns a mutable version of a frozen message.

    Will return None if called with None.
    """
    ...

