"""
This type stub file was generated by pyright.
"""

"""
Read and write SYX file format
"""
def read_syx_file(filename): # -> list[Any]:
    """Read sysex messages from SYX file.

    Returns a list of sysex messages.

    This handles both the text (hexadecimal) and binary
    formats. Messages other than sysex will be ignored. Raises
    ValueError if file is plain text and byte is not a 2-digit hex
    number.
    """
    ...

def write_syx_file(filename, messages, plaintext=...): # -> None:
    """Write sysex messages to a SYX file.

    Messages other than sysex will be skipped.

    By default this will write the binary format.  Pass
    ``plaintext=True`` to write the plain text format (hex encoded
    ASCII text).
    """
    ...

