"""
This type stub file was generated by pyright.
"""

class Tokenizer:
    """
    Splits a MIDI byte stream into messages.
    """
    def __init__(self, data=...) -> None:
        """Create a new decoder."""
        ...
    
    def feed_byte(self, byte): # -> None:
        """Feed MIDI byte to the decoder.

        Takes an int in range [0..255].
        """
        ...
    
    def feed(self, data): # -> None:
        """Feed MIDI bytes to the decoder.

        Takes an iterable of ints in in range [0..255].
        """
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        """Yield messages that have been parsed so far."""
        ...
    


