"""
This type stub file was generated by pyright.
"""

def is_node(value): # -> bool:
    ...

def is_shape(value): # -> bool:
    ...

def collect_array(a_value, base, nodes):
    ...

def collect_union(type_list, base, nodes):
    ...

def collect_object(o_value, base, nodes):
    ...

def collect_nodes(metadata, base=..., nodes=...): # -> list[Any]:
    ...

def filter_base_nodes(nodes): # -> list[Any]:
    ...

