"""
This type stub file was generated by pyright.
"""

from .checks import check_time
from .messages import BaseMessage, Message, format_as_string, parse_string, parse_string_stream
from .specs import MAX_PITCHWHEEL, MAX_SONGPOS, MIN_PITCHWHEEL, MIN_SONGPOS, SPEC_BY_STATUS, SPEC_BY_TYPE, SPEC_LOOKUP

__all__ = ["BaseMessage", "MAX_PITCHWHEEL", "MAX_SONGPOS", "MIN_PITCHWHEEL", "MIN_SONGPOS", "Message", "SPEC_BY_STATUS", "SPEC_BY_TYPE", "SPEC_LOOKUP", "check_time", "format_as_string", "parse_string", "parse_string_stream"]
