"""
This type stub file was generated by pyright.
"""

_SPECIAL_CASES = ...
def decode_message(msg_bytes, time=..., check=...): # -> dict[str, Any | int]:
    """Decode message bytes and return messages as a dictionary.

    Raises ValueError if the bytes are out of range or the message is
    invalid.

    This is not a part of the public API.
    """
    ...

