"""
This type stub file was generated by pyright.
"""

_SPECIAL_CASES = ...
def encode_message(msg): # -> list[Any] | list[int | Any]:
    """Encode msg dict as a list of bytes.

    TODO: Add type and value checking.
          (Can be turned off with keyword argument.)

    This is not a part of the public API.
    """
    ...

