"""
This type stub file was generated by pyright.
"""

def msg2str(msg, include_time=...): # -> str:
    ...

def str2msg(text): # -> dict[str, Any | int | tuple[()]]:
    """Parse str format and return message dict.

    No type or value checking is done. The caller is responsible for
    calling check_msgdict().
    """
    ...

