"""
This type stub file was generated by pyright.
"""

from .meta import KeySignatureError, MetaMessage, UnknownMetaMessage
from .midifiles import MidiFile
from .tracks import MidiTrack, merge_tracks
from .units import bpm2tempo, second2tick, tempo2bpm, tick2second

__all__ = ["KeySignatureError", "MetaMessage", "MidiFile", "MidiTrack", "UnknownMetaMessage", "bpm2tempo", "merge_tracks", "second2tick", "tempo2bpm", "tick2second"]
