"""
This type stub file was generated by pyright.
"""

from .dependencies import ALL, ALLSMALLER, ClientsideFunction, Input, MATCH, Output, State
from . import dash_table, dcc, development, exceptions, html, resources
from .version import __version__
from ._callback_context import callback_context, set_props
from ._callback import callback, clientside_callback
from ._get_app import get_app
from ._get_paths import get_asset_url, get_relative_path, strip_relative_path
from .long_callback import CeleryManager, DiskcacheManager
from ._pages import PAGE_REGISTRY as page_registry, register_page
from .dash import Dash, no_update, page_container
from ._patch import Patch
from ._jupyter import jupyter_dash

__plotly_dash = ...
ctx = ...
