"""
This type stub file was generated by pyright.
"""

from . import dash_table, development, exceptions, resources
from . import dcc as dcc
from . import html as html
from ._callback import callback, clientside_callback
from ._callback_context import callback_context, set_props
from ._get_app import get_app
from ._get_paths import get_asset_url, get_relative_path, strip_relative_path
from ._jupyter import jupyter_dash
from ._pages import PAGE_REGISTRY as page_registry
from ._pages import register_page
from ._patch import Patch
from .dash import Dash as Dash
from .dash import no_update, page_container
from .dependencies import (
    ALL,
    ALLSMALLER,
    MATCH,
    ClientsideFunction,
    Input,
    Output,
    State,
)
from .long_callback import CeleryManager, DiskcacheManager
from .version import __version__

__plotly_dash = ...
ctx = ...
