"""
This type stub file was generated by pyright.
"""

class Resources:
    def __init__(self, resource_name) -> None:
        ...
    
    def append_resource(self, resource): # -> None:
        ...
    
    def get_all_resources(self, dev_bundles=...): # -> list[Any]:
        ...
    
    def get_library_resources(self, libraries, dev_bundles=...): # -> list[Any]:
        ...
    


class _Config:
    def __init__(self, serve_locally, eager_loading) -> None:
        ...
    


class Css:
    def __init__(self, serve_locally) -> None:
        ...
    
    def append_css(self, stylesheet): # -> None:
        ...
    
    def get_all_css(self): # -> list[Any]:
        ...
    
    def get_library_css(self, libraries): # -> list[Any]:
        ...
    


class Scripts:
    def __init__(self, serve_locally, eager) -> None:
        ...
    
    def append_script(self, script): # -> None:
        ...
    
    def get_all_scripts(self, dev_bundles=...): # -> list[Any]:
        ...
    
    def get_library_scripts(self, libraries, dev_bundles=...): # -> list[Any]:
        ...
    


