"""
This type stub file was generated by pyright.
"""

import inspect
import hashlib
from abc import ABC

class BaseLongCallbackManager(ABC):
    UNDEFINED = ...
    managers = ...
    functions = ...
    def __init__(self, cache_by) -> None:
        ...
    
    def terminate_job(self, job):
        ...
    
    def terminate_unhealthy_job(self, job):
        ...
    
    def job_running(self, job):
        ...
    
    def make_job_fn(self, fn, progress, key=...):
        ...
    
    def call_job_fn(self, key, job_fn, args, context):
        ...
    
    def get_progress(self, key):
        ...
    
    def result_ready(self, key):
        ...
    
    def get_result(self, key, job):
        ...
    
    def get_updated_props(self, key):
        ...
    
    def build_cache_key(self, fn, args, cache_args_to_ignore): # -> str:
        ...
    
    def register(self, key, fn, progress): # -> None:
        ...
    
    @staticmethod
    def register_func(fn, progress, callback_id): # -> str:
        ...
    
    @staticmethod
    def hash_function(fn, callback_id=...): # -> str:
        ...
    


